import pyttsx3
friend=pyttsx3.init()
#friend.Getproperty("voice")
#friend.Setproperty("voices",voice[1].id)
#print("voice")
friend.say("good morning students")
friend.runAndWait()
friend.say("shivamani how are you today?")
friend.runAndWait()
print("al the very best")
#x=input("enter anything")
#friend.say(x)
#friend.runAndWait()
friend.say("hello sir, my name is DAVID")
friend.runAndWait()
friend.say("im your voice assistant")
friend.runAndWait()
friend.say("you can ask me anything you want")
friend.runAndWait()
friend.say("please ask me,please")
friend.runAndWait()
friend.say("ok do you think im fake?")
friend.runAndWait()
friend.say("yea now your lisnin'")
friend.runAndWait()
friend.say("im talking to you sir chakradhar")
friend.runAndWait()
